packages:
  - packages/*
  - apps/*
catalog:
  "@ariakit/react": 0.4.17
  "@babel/preset-typescript": 7.27.1
  "@chromatic-com/storybook": 4.0.1
  "@eslint/js": 9.30.1
  "@graphql-eslint/eslint-plugin": 4.4.0
  "@hono/node-server": 1.15.0
  "@iconify-json/material-symbols": 1.2.29
  "@inlang/paraglide-js": 2.2.0
  "@material/material-color-utilities": 0.3.0
  "@playwright/test": 1.53.2
  "@react-router/dev": 7.6.3
  "@react-router/node": 7.6.3
  "@sentry/react": 9.35.0
  "@sentry/toolbar": 1.0.0-beta.11
  "@sentry/vite-plugin": 3.5.0
  "@storybook/addon-a11y": 9.1.0-alpha.6
  "@storybook/addon-docs": 9.1.0-alpha.6
  "@storybook/addon-onboarding": 9.1.0-alpha.6
  "@storybook/addon-themes": 9.1.0-alpha.6
  "@storybook/addon-vitest": 9.1.0-alpha.6
  "@storybook/react-vite": 9.1.0-alpha.6
  "@stryker-mutator/api": 9.0.1
  "@stryker-mutator/core": 9.0.1
  "@stryker-mutator/vitest-runner": 9.0.1
  "@svgr/core": 8.1.0
  "@svgr/plugin-jsx": 8.1.0
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.1.11
  "@types/bun": 1.2.18
  "@types/estree": 1.0.8
  "@types/marked": 0.3.0
  "@types/node": 22.16.0
  "@types/prop-types": 15.7.15
  "@types/react": 19.1.8
  "@types/react-dom": 19.1.6
  "@types/react-relay": 18.2.1
  "@types/relay-runtime": 19.0.2
  "@typescript-eslint/parser": 8.36.0
  anitomy: 0.0.35
  arktype: 2.1.20
  babel-plugin-react-compiler: 19.1.0-rc.2
  cookie: 1.0.2
  cross-env: 7.0.3
  csstype: 3.1.3
  dompurify: 3.2.5
  dotenv: 17.1.0
  electron: 35.7.0
  electron-devtools-installer: 4.0.0
  eslint: 9.30.1
  eslint-plugin-oxlint: 1.6.0
  eslint-plugin-pnpm: 1.0.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-compiler: beta
  eslint-plugin-react-hooks: 6.0.0-rc1
  eslint-plugin-react-refresh: 0.4.20
  eslint-plugin-storybook: 9.1.0-alpha.6
  eslint-plugin-turbo: 2.5.4
  eslint-typegen: 2.2.1
  eslint-vitest-rule-tester: 2.2.0
  framer-motion: 12.23.0
  graphql: 16.11.0
  graphql-config: 5.1.5
  hono: 4.8.4
  isbot: 5.1.28
  knip: 5.61.3
  marked: 0.3.19
  nodemon: 3.1.10
  oxlint: 1.6.0
  prettier: 3.6.2
  prettier-plugin-tailwindcss: 0.6.13
  prop-types: 15.8.1
  react: 19.1.0
  react-dom: 19.1.0
  react-relay: 20.0.0
  react-router: 7.6.3
  relay-compiler: 20.0.0
  relay-runtime: 20.0.0
  storybook: 9.1.0-alpha.6
  stryker-cli: 1.0.2
  tailwind-variants: npm:@patryk_walach/tailwind-variants@0.2.1
  tailwindcss: 4.1.11
  tsx: 4.20.3
  turbo: 2.5.4
  typescript: 5.8.3
  typescript-eslint: 8.36.0
  unplugin-icons: 22.1.0
  vite: 7.0.2
  vite-plugin-babel: 1.3.2
  vite-plugin-inspect: 11.3.0
  vite-plugin-relay: 2.1.0
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  wrangler: 4.23.0
  "@msw/playwright": 0.4.2
  msw: 2.10.3
  "@graphql-tools/mock": 9.0.23
  "@prettier/plugin-oxc": 0.0.4

catalogs:
  experimental:
    vite: npm:rolldown-vite@7.0.5
