packages:
  - packages/*
  - apps/*
catalog:
  "@ariakit/react": 0.4.17
  "@babel/preset-typescript": 7.27.1
  "@chromatic-com/storybook": 3.2.6
  "@eslint/js": 9.27.0
  "@graphql-eslint/eslint-plugin": 4.4.0
  "@hono/node-server": 1.14.3
  "@iconify-json/material-symbols": 1.2.21
  "@inlang/paraglide-js": 2.0.13
  "@material/material-color-utilities": 0.3.0
  "@playwright/test": 1.52.0
  "@react-router/dev": 7.6.0
  "@react-router/node": 7.6.0
  "@sentry/react": 9.22.0
  "@sentry/toolbar": 1.0.0-beta.11
  "@sentry/vite-plugin": 3.5.0
  "@storybook/addon-a11y": 8.6.14
  "@storybook/addon-essentials": 8.6.14
  "@storybook/addon-onboarding": 8.6.14
  "@storybook/addon-themes": 8.6.14
  "@storybook/experimental-addon-test": 8.6.14
  "@storybook/react": 8.6.14
  "@storybook/react-vite": 8.6.14
  "@storybook/test": 8.6.14
  "@svgr/core": 8.1.0
  "@svgr/plugin-jsx": 8.1.0
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.1.7
  "@types/bun": 1.2.14
  "@types/estree": 1.0.7
  "@types/marked": 0.3.0
  "@types/node": 22.15.21
  "@types/prop-types": 15.7.14
  "@types/react": 19.1.5
  "@types/react-dom": 19.1.5
  "@types/react-relay": 18.2.1
  "@types/relay-runtime": 19.0.1
  "@typescript-eslint/parser": 8.32.1
  anitomy: 0.0.35
  arktype: 2.1.20
  babel-plugin-react-compiler: 19.1.0-rc.2
  cookie: 1.0.2
  cross-env: 7.0.3
  csstype: 3.1.3
  dompurify: 3.2.5
  dotenv: 16.5.0
  electron: 35.2.2
  electron-devtools-installer: 4.0.0
  eslint: 9.27.0
  eslint-plugin-oxlint: 0.16.12
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 6.0.0-rc1
  eslint-plugin-react-refresh: 0.4.20
  eslint-plugin-storybook: 0.12.0
  eslint-plugin-turbo: 2.5.3
  eslint-typegen: 2.2.0
  eslint-vitest-rule-tester: 2.2.0
  framer-motion: 12.15.0
  graphql: 16.11.0
  graphql-config: 5.1.5
  hono: 4.7.10
  isbot: 5.1.28
  knip: 5.58.1
  marked: 0.3.19
  nodemon: 3.1.10
  oxlint: 0.16.12
  prettier: 3.5.3
  prettier-plugin-tailwindcss: 0.6.11
  prop-types: 15.8.1
  react: 19.1.0
  react-dom: 19.1.0
  react-relay: 19.0.0
  react-router: 7.6.0
  relay-compiler: 19.0.0
  relay-runtime: 19.0.0
  storybook: 8.6.14
  tailwind-variants: npm:@patryk_walach/tailwind-variants@0.2.1
  tailwindcss: 4.1.7
  tsx: 4.19.4
  turbo: 2.5.3
  typescript: 5.8.3
  typescript-eslint: 8.32.1
  unplugin-icons: 22.1.0
  vite: 6.3.5
  vite-plugin-babel: 1.3.1
  vite-plugin-inspect: 11.1.0
  vite-plugin-oxlint: 1.3.3
  vite-plugin-relay: 2.1.0
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.4
  wrangler: 4.16.1
