name: Install playwright 📦
description: Installs Playwright dependencies

runs:
  using: composite
  steps:
    - name: Playwright version
      shell: bash
      run: echo "version=$(pnpm exec playwright --version)" >> "$GITHUB_OUTPUT"
      id: playwright

    - name: Cache playwright binaries
      id: cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright.outputs.version }}
      if: runner.os != 'Windows'

    - name: Cache playwright binaries
      id: cache-windows
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: |
          ~\AppData\Local\ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright.outputs.version }}
      if: runner.os == 'Windows'

    - name: Install playwright 📦
      shell: bash
      run: pnpm --filter=web exec playwright install chromium-headless-shell webkit --with-deps
