name = "web-flags"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Created for you by `flaghoist deploy`, or by: npx wrangler kv namespace create web-flags-FLAGS
kv_namespaces = [{ binding = "FLAGS", id = "427845372c20404399501b8d313bcff8" }]
[[previews]]
kv_namespaces = [{ binding = "FLAGS", id = "427845372c20404399501b8d313bcff8" }]
