name: Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - renovate/**
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Audit
        run: pnpm audit
