name: CodSpeed

on:
  push:
    branches:
      - master
      - renovate/**
  pull_request:
  # merge_group: # codespeed does not support merge groups
  workflow_dispatch:

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_CACHE: remote:rw
  TURBO_SCM_BASE: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.before }}

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - name: Install Socket Firewall
        uses: socketdev/action@ba6de6cc0565af1f42295590380973573297e31f
        with:
          mode: firewall-free
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: blob:none
          fetch-depth: 0
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          package-manager-cache: false

      - name: Install dependencies 📦
        run: sfw pnpm install --frozen-lockfile --prefer-offline

      - name: Run benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5.2.1
        with:
          run: pnpm exec turbo bench
          mode: simulation
        timeout-minutes: 5
