name: CodSpeed

on:
  push:
    branches:
      - master
      - renovate/**
  pull_request:
  # merge_group: # codespeed does not support merge groups
  workflow_dispatch:

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_CACHE: remote:rw
  TURBO_SCM_BASE: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.before }}

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref_name != 'master' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pnpm exec vitest bench --run
