name: Test

on:
  push:
    branches:
      - master
      - renovate/**
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_CACHE: remote:rw
  TURBO_SCM_BASE: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.before }}

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref_name != 'master' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy-sentry:
    name: Deploy Sentry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm exec turbo --filter=@anitrove/web build

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: apps/web/build
  deploy:
    name: Deploy Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm exec turbo --filter=@anitrove/web build

      - name: Deploy
        run: pnpm exec wrangler pages deploy --branch=${{ github.head_ref || github.ref_name  }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  stryker:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Check
        run: pnpm exec turbo check

      - name: Cache Incremental
        uses: actions/cache@v4
        with:
          path: reports/stryker-incremental.json
          key: stryker-incremental
          enableCrossOsArchive: true

      - name: Coverage
        run: pnpm exec turbo stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_KEY }}
