name: GitHub Workflows Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * *"
permissions:
  actions: read
  issues: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/github-workflows-metrics@a818cf0910e7cbb54dddb587879c562ea083dfa4
        with:
          status: success
