name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Test E2E
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.3-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Install unzip
        shell: bash
        run: |
          apt-get update
          apt-get install -y unzip
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Test E2E
        run: bun run test
        env:
          ANILIST_TEST_TOKEN: ${{ secrets.ANILIST_TEST_TOKEN }}

  typecheck:
    runs-on: ubuntu-latest

    name: Typecheck
    steps:
      - uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - run: bun run paraglide

      - name: Typecheck
        run: bun run --bun check

  format:
    runs-on: ubuntu-latest
    name: Lint & Format
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run --bun lint --fix

      - name: Format
        run: bun run --bun format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: run format"
