name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Test E2E
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.3-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Install unzip
        shell: bash
        run: |
          apt-get update
          apt-get install -y unzip
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Test E2E
        run: bun run test
        env:
          HOME: /root

  typecheck:
    runs-on: ubuntu-latest

    name: Typecheck
    steps:
      - uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run check
