name: Test

on:
  push:
    branches:
      - renovate/**
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_CACHE: remote:rw
  TURBO_SCM_BASE: ${{ github.event.merge_group.base_sha || github.event.pull_request.base.sha || github.event.before }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy@sha256:4698a73749c5848d3f5fcd42a2174d172fcad2b2283e087843b115424303a565
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Test E2E
        run: pnpm -w test-e2e

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Typecheck
        run: pnpm -w check

  knip:
    runs-on: ubuntu-latest

    name: Knip
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Relay
        run: pnpm exec turbo relay router paraglide

      - name: Knip
        run: pnpm exec turbo knip

  boundaries:
    runs-on: ubuntu-latest

    name: Boundaries
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Boundaries
        run: pnpm -w boundaries
  doctor:
    runs-on: ubuntu-latest

    name: Doctor
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Doctor
        run: pnpm doctor
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v6
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Test
        run: pnpm exec turbo test
